services:
  web:
    build: .
    ports:
      - '1443:1443'
    environment:
      NODE_ENV: production
      PORT: 1443
      REDIS_HOST: redis
      BASE_URL: http://localhost:1443
    depends_on:
      - redis

  redis:
    image: redis:8-alpine
    ports:
      - '6379:6379'
